## this file will be loaded only in the development environment
server:
  port: 8080

logging:
  file:
    name: chronos.log
  level:
    it:
      addvalue:
        chronos: DEBUG
      org:
        hibernate:
          SQL: DEBUG
        springframework:
          web: DEBUG



