## this file will be loaded for both the development and production environments

## the @spring.profiles.active@ placeholder will be replaced when the application starts.
## the default value of the property spring.profiles.active is 'dev' and it is defined in the pom.xml 
## within the <profiles> tags (note that there is a <profiles> tag also within the spring-boot-maven-plugin plugin)
spring:
  profiles:
    active: '@spring.profiles.active@'
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://172.31.2.20:1433;DatabaseName=DB_GPA_ASL
    username: ASL
    password: "@SL-21-3!"
  jpa:
    hibernate:
      ddl-auto: none # Hibernate ddl auto (create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
    show-sql: true

server:
  servlet:
    context-path: /chronos


##
# Actuator 
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints
# http://localhost:[port]/chronos/actuator/info
##
info:
  application:
    author: Add Value
    description: Add Value Chronos
    name: chronos
    version: 0.0.1-SNAPSHOT

